### ISSUE TITLE
Error with redis: redis/redis.sock. No such file or directory.

### ISSUE THREAD

**Issue by Khady** [onitu/onitu#1]
I try to launch onitu on OSX. But redis can't find the file `redis/redis.sock`. Onitu loop on this error.

I tried to add a sleep in the referee and the loader to be sure that redis have enough time to start before onitu, but it doesn't fix the problem.

```
$ ./onitu.sh
2013-11-18 01:07:54 [15741] [WARNING] error in 'redis': [Errno 2] No such file or directory
2013-11-18 01:07:54 [15741] [WARNING] error in 'redis': [Errno 2] No such file or directory
2013-11-18 01:07:54 [15741] [WARNING] error in 'redis': [Errno 2] No such file or directory
2013-11-18 01:07:54 [15741] [WARNING] error in 'redis': [Errno 2] No such file or directory
2013-11-18 01:07:54 [15741] [WARNING] error in 'redis': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/louisroche/Code/epitech/onitu/onitu/referee/__main__.py", line 10, in <module>
    referee = Referee()
  File "onitu/referee/referee.py", line 40, in __init__
    self.redis.set('referee:publisher', port)
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/client.py", line 808, in set
    return self.execute_command('SET', *pieces)
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/client.py", line 397, in execute_command
    connection.send_command(*args)
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/connection.py", line 306, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/connection.py", line 288, in send_packed_command
    self.connect()
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/connection.py", line 235, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: redis/redis.sock. No such file or directory.
[2013-11-17 17:07] INFO: Loader: Loading entry A
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/louisroche/Code/epitech/onitu/onitu/loader.py", line 32, in <module>
    redis.hmset('drivers:{}:options'.format(name), conf['options'])
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/client.py", line 1431, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/client.py", line 397, in execute_command
    connection.send_command(*args)
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/connection.py", line 306, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/connection.py", line 288, in send_packed_command
    self.connect()
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/connection.py", line 235, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: redis/redis.sock. No such file or directory.
```

**Comment by k4nar** [comment]
What version of Redis do you have ?

Does `touch redis/redis.sock` before launching Onitu resolve the issue ?

**Comment by Khady** [comment]
> What version of Redis do you have ?

```
$ redis-server --version                                                                                                                                                  
Redis server v=2.6.14 sha=00000000:0 malloc=libc bits=64
```

> Does touch redis/redis.sock before launching Onitu resolve the issue ?

```
$ touch redis/redis.sock
$ ./onitu.sh
2013-11-19 12:04:36 [25898] [WARNING] error in 'redis': [Errno 2] No such file or directory
2013-11-19 12:04:36 [25898] [WARNING] error in 'redis': [Errno 2] No such file or directory
2013-11-19 12:04:36 [25898] [WARNING] error in 'redis': [Errno 2] No such file or directory
2013-11-19 12:04:36 [25898] [WARNING] error in 'redis': [Errno 2] No such file or directory
2013-11-19 12:04:36 [25898] [WARNING] error in 'redis': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/louisroche/Code/epitech/onitu/onitu/referee/__main__.py", line 10, in <module>
    referee = Referee()
  File "onitu/referee/referee.py", line 40, in __init__
    self.redis.set('referee:publisher', port)
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/client.py", line 808, in set
    return self.execute_command('SET', *pieces)
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/client.py", line 397, in execute_command
    connection.send_command(*args)
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/connection.py", line 306, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/connection.py", line 288, in send_packed_command
    self.connect()
  File "/Users/louisroche/Code/epitech/onitu/lib/python2.7/site-packages/redis/connection.py", line 235, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 38 connecting to unix socket: redis/redis.sock. Socket operation on non-socket.
```

**Comment by k4nar** [comment]
Okay, let's try to launch Redis by hand : `redis-server redis/redis.conf`. Then wait a few seconds, kill it and read `redis/redis.log`.

**Comment by Khady** [comment]
fix in 3dd1deea7

**Comment by k4nar** [comment]
Ok, it seems that the issue was that the 'redis-server' executable wasn't found without the $PATH env variable.

**Comment by slapglif** [comment]
inside of docker containers, particularly kali - the problem is that the redis-server service is not running, the issue is due to a number of permission errors due to the default configuration and stripped down nature of containers.

assuming you have installed redis, just be sure you have all of the packages anyway -

`apt-get install redis*`

The problem is fixed with a simple:

`chmod 700 /var/log/redis/redis-server.log`

and just for good measure,

`ln -s /var/run/redis/redis.sock /tmp/redis.sock`

then 

`service redis-server restart && service redis-server status`

if it say anything other than OK, I have no idea what I'm talking about.
