### ISSUE TITLE
crash on first launch

### ISSUE THREAD

**Issue by wapiflapi** [onitu/onitu#13]
When first started onitu crashes because it can find some plug options. This might be do to them not being corectly commited to the redis DB.

How to reproduce:

```
# stop redis
rm redis/appendonly.aof redis/redis.log
# start redis
python -m onitu
```

output (notice the log is printed twice):

```
connecting.
[2014-02-26 23:48] INFO: Onitu: Loading setup...
connecting.
[2014-02-26 23:48] INFO: Referee: Started
connecting.
connecting.
[2014-02-26 23:48] INFO: B: Started
[2014-02-26 23:48] INFO: A: Started
[2014-02-26 23:48] INFO: B - Router: Started
[2014-02-26 23:48] INFO: A - Router: Started
[2014-02-26 23:48] INFO: A - Dealer: Started
[2014-02-26 23:48] INFO: B - Dealer: Started
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
    exec code in run_globals
  File "/home/wapiflapi/Projects/onitu/onitu/drivers/local_storage/__main__.py", line 9, in <module>
  File "/home/wapiflapi/Projects/onitu/onitu/drivers/local_storage/__main__.py", line 9, in <module>
    start(sys.argv[1])
    start(sys.argv[1])
  File "onitu/drivers/local_storage/local_storage.py", line 146, in start
  File "onitu/drivers/local_storage/local_storage.py", line 146, in start
    root = path(plug.options['root'])
    root = path(plug.options['root'])
KeyError: 'root'KeyError
```

**Comment by k4nar** [comment]
What's your `setup.json` ? I bet that's the issue here :) .

**Comment by wapiflapi** [comment]
Default one, and I didn't change it between the first run (that fails) and the second one (working).
I supose if the setup was the problem it wouldn't work the second time would it?

**Comment by k4nar** [comment]
Okay so apparently you were using your own instance of Redis or something. I don't reckon this is directly linked to Onitu.
