### ISSUE TITLE
Crash in LocalStorage

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#23]
This happened during the demo : 

It was due to the renaming of a directory with Nautilus. However, it shouldn't crash but only log the error.

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/rozo_a/Projects/onitu/onitu/env/lib/python2.7/site-packages/pyinotify.py", line 1511, in run
    self.loop()
  File "/home/rozo_a/Projects/onitu/onitu/env/lib/python2.7/site-packages/pyinotify.py", line 1497, in loop
    self.process_events()
  File "/home/rozo_a/Projects/onitu/onitu/env/lib/python2.7/site-packages/pyinotify.py", line 1295, in process_events
    self._default_proc_fun(revent)
  File "/home/rozo_a/Projects/onitu/onitu/env/lib/python2.7/site-packages/pyinotify.py", line 937, in __call__
    return _ProcessEvent.__call__(self, event)
  File "/home/rozo_a/Projects/onitu/onitu/env/lib/python2.7/site-packages/pyinotify.py", line 662, in __call__
    return meth(event)
  File "onitu/drivers/local_storage/local_storage.py", line 115, in process_IN_CLOSE_WRITE
    update_file(metadata, abs_path)
  File "onitu/drivers/local_storage/local_storage.py", line 19, in update_file
    metadata.size = path.size
  File "/home/rozo_a/Projects/onitu/onitu/env/lib/python2.7/site-packages/path.py", line 1050, in getsize
    return self.module.getsize(self)
  File "/home/rozo_a/Projects/onitu/onitu/env/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/home/rozo_a/Projects/onitu/onitu/example/driver_a/Nouveau dossier/file.png'
```

**Comment by k4nar** [comment]
Could someone check with Nautilus if now we have the right behavior (that is, "New file.txt" is created, and then moved to "whatever_you_name_it.txt") ?

**Comment by Scylardor** [comment]
I just checked and I don't think so.

When you go "New Document -> Empty Document" in Nautilus, it creates an 'Untitled Document' file, which is detected by Onitu, but renaming it, upon creation (Nautilus lets you edit its name right away) or later doesn't do anything in Onitu.

It doesn't crash anymore though.

EDIT : I take that back. It still crashes with folders :

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/baron_a/.virtualenvs/onitu/local/lib/python2.7/site-packages/pyinotify.py", line 1511, in run
    self.loop()
  File "/home/baron_a/.virtualenvs/onitu/local/lib/python2.7/site-packages/pyinotify.py", line 1497, in loop
    self.process_events()
  File "/home/baron_a/.virtualenvs/onitu/local/lib/python2.7/site-packages/pyinotify.py", line 1295, in process_events
    self._default_proc_fun(revent)
  File "/home/baron_a/.virtualenvs/onitu/local/lib/python2.7/site-packages/pyinotify.py", line 937, in __call__
    return _ProcessEvent.__call__(self, event)
  File "/home/baron_a/.virtualenvs/onitu/local/lib/python2.7/site-packages/pyinotify.py", line 662, in __call__
    return meth(event)
  File "onitu/drivers/local_storage/local_storage.py", line 234, in process_IN_CLOSE_WRITE
    self.process_event(event, update)
  File "onitu/drivers/local_storage/local_storage.py", line 247, in process_event
    callback(metadata, abs_path)
  File "onitu/drivers/local_storage/local_storage.py", line 33, in update
    "Error updating file '{}': {}".format(metadata.filename, e)
ServiceError: Error updating file 'Untitled Folder/same': [Errno 2] No such file or directory: '/home/baron_a/Projects/EIP/onitu/example/driver_a/Untitled Folder/same'
```

Happens upon placing a file in the folder after having renamed it.

**Comment by k4nar** [comment]
Were you trying with the last version on develop ?

**Comment by Scylardor** [comment]
Actually I wasn't, but trying the last version is the same.

It seems like it kind of stalls events too. Any file dropped in the driver_{a,b} example folders isn't detected anymore by Onitu after that, that's weird

**Comment by k4nar** [comment]
Well, a good old "remove the database & retry" should fix it ;) .

**Comment by Scylardor** [comment]
After a bit of cleaning, that's still no good. In short, what happens : 
- renaming a regular file works, the update is detected and there's the message `INFO: Referee: Moving of 'yolo' to 'swag' from A`
- creating an untitled document in Nautilus is detected by Onitu but renaming it, later or on the spot, isn't detected. Moreso, doing it seems to break any subsequent attempt too and Onitu doesn't detect any move after that (even in terminal)
- when creating a new folder in Nautilus, Onitu doesn't detect the folder creation (maybe normal). Nothing happens either when we rename the folder. And it crashes when we try to put a file in the renamed folder.

When you try with multiple new files, it also seems the old key of the first "Untitled Document" isn't removed from the database, as the first time you do it, Onitu notifies `INFO: Referee: Update for '/Untitled Document' from A`, but not with the subsequent tries.

Also, had a weird error as I reloaded Onitu, since it seemed nothing was updated : 

```
[2014-07-19 16:12] INFO: Referee: Moving of 'yolo' to 'swag' from A
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "onitu/referee/referee.py", line 70, in listen
    self.handlers[cmd](fid, *args[1:])
  File "onitu/referee/referee.py", line 138, in _handle_move
    new_metadata = self.escalator.get('file:{}'.format(new_fid))
  File "onitu/escalator/client/escalator.py", line 71, in get
    value = self._request(protocol.cmd.GET, key)[0]
  File "onitu/escalator/client/escalator.py", line 29, in _request
    return protocol.msg.extract_response(self.socket.recv())
  File "onitu/escalator/protocol/msg.py", line 40, in extract_response
    raise status.exception(*args)
KeyNotFound: "Key 'file:4b8cd4ba-11ea-53e3-946c-94062dacc772' not found in base"
```

**Comment by k4nar** [comment]
Yeah, I think what happens here is that we have a weird issue when creating a file with Nautilus, causing a lot of bugs. The behavior of Onitu can be quite weird when some events are wrong, I should try to fix that someday.

I really don't understand why Onitu wouldn't detect the renaming when creating a file. Could you run it with `--debug`, and maybe print the `event` variable in `process_IN_MOVE_TO` in LocalStorage.
