### ISSUE TITLE
Issue when sharing the database with Python 2 and 3

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#62]
We have some unicode-related issues when sharing the DB. Here is the Traceback using Python 3 with a database created with Python 2: 

```
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yannick/Onitu/onitu/onitu/drivers/local_storage/local_storage.py", line 268, in start
    check_changes()
  File "/home/yannick/Onitu/onitu/onitu/drivers/local_storage/local_storage.py", line 53, in check_changes
    metadata = plug.get_metadata(filename)
  File "/home/yannick/Onitu/onitu/onitu/plug/plug.py", line 169, in get_metadata
    metadata = Metadata.get_by_filename(self, filename)
  File "/home/yannick/Onitu/onitu/onitu/plug/metadata.py", line 58, in get_by_filename
    return cls.get_by_id(plug, fid)
  File "/home/yannick/Onitu/onitu/onitu/plug/metadata.py", line 72, in get_by_id
    metadata = cls(plug, fid=fid, **values)
TypeError: __init__() keywords must be strings
```

When printing the metadata, I was getting keys in bytes instead of string. This is the source of the issue.

**Comment by k4nar** [comment]
We need a volunteer for this one.

**Comment by Scylardor** [comment]
I'm on it.

**Comment by Scylardor** [comment]
So far I think 0d36ed7975cf98836e3e20842d72a40d4c40375a fixed it.

Can someone confirm ?

**Comment by k4nar** [comment]
Could you break your commit into pieces ?

**Comment by Scylardor** [comment]
As this fix isn't very stable, I didn't include it in the new commit split.

It should be done at a deeper level of Onitu.
