### ISSUE TITLE
AttributeError in Metadata

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#8]
I just got this traceback:

```
[2014-02-16 14:27] INFO: Onitu: Loading setup...
[2014-02-16 14:27] INFO: Referee: Started
[2014-02-16 14:27] INFO: A: Started
[2014-02-16 14:27] INFO: A - Router: Started
[2014-02-16 14:27] INFO: B: Started
[2014-02-16 14:27] INFO: B - Router: Started
[2014-02-16 14:27] INFO: A - Dealer: Started
[2014-02-16 14:27] INFO: B - Dealer: Started
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yannick/Onitu/onitu/onitu/drivers/local_storage/__main__.py", line 9, in <module>
    start(sys.argv[1])
  File "onitu/drivers/local_storage/local_storage.py", line 156, in start
    check_changes()
  File "onitu/drivers/local_storage/local_storage.py", line 89, in check_changes
    metadata = plug.get_metadata(filename)
  File "onitu/api/plug.py", line 139, in get_metadata
    metadata = Metadata.get_by_filename(self, filename)
  File "onitu/api/metadata.py", line 42, in get_by_filename
    return cls.get_by_id(plug, fid)
  File "onitu/api/metadata.py", line 56, in get_by_id
    metadata.__setattr__(name, deserialize(values.get(name)))
  File "onitu/api/metadata.py", line 19, in <lambda>
    'uptodate': (lambda e: e.split(':'), lambda l: ':'.join(l)),
AttributeError: 'NoneType' object has no attribute 'split'
[2014-02-16 14:27] INFO: Referee: New event for 'foo' from A
[2014-02-16 14:27] INFO: Referee: New event for 'toto' from A
[2014-02-16 14:27] INFO: Referee: New event for 'lol' from A
```

I had the three files `foo`, `toto` and `lol` in both drivers, but no `appendonly.aof`. I think @Akiat had the same issue once.

**Comment by k4nar** [comment]
This is the Traceback @Akiat had :

```
File "onitu/drivers/local_storage/local_storage.py", line 102, in on_modified
   self._handle_update(event.src_path)
 File "onitu/drivers/local_storage/local_storage.py", line 119, in _handle_update
   metadata = plug.get_metadata(filename)
 File "onitu/api/plug.py", line 135, in get_metadata
   metadata = Metadata.get_by_filename(self, filename)
 File "onitu/api/metadata.py", line 39, in get_by_filename
   return cls.get_by_id(plug, fid)
 File "onitu/api/metadata.py", line 54, in get_by_id
   metadata.__setattr__(name, deserialize(values.get(name)))
 File "onitu/api/metadata.py", line 19, in <lambda>
   'uptodate': (lambda e: e.split(':'), lambda l: ':'.join(l)),
AttributeError: 'NoneType' object has no attribute 'split'
```
