### ISSUE TITLE
Remove errors on close

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#86]
When we close Onitu, we sometimes get weird errors. This actually expected and should not be an issue, but we should catch those exceptions and hide them.

Example of error : 

```
^C[2014-09-14 18:34] INFO: Onitu: Exiting...
[2014-09-14 18:34] INFO: Escalator: Exited
[2014-09-14 18:34] INFO: Referee: Exited
[2014-09-14 18:34] INFO: A: Exited
[2014-09-14 18:34] INFO: B: Exited

^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/baron_a/Projects/EIP/onitu/onitu/__main__.py", line 237, in <module>
    loop.run_sync(arbiter.stop)
  File "/home/baron_a/.virtualenvs/onitu/local/lib/python2.7/site-packages/tornado/ioloop.py", line 417, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
tornado.ioloop.TimeoutError: Operation timed out after None seconds
Exception in thread Thread-11:                                                                                         [20:34]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "onitu/drivers/dropbox/dropbox_driver.py", line 271, in run
    self.check_dropbox()
  File "onitu/drivers/dropbox/dropbox_driver.py", line 263, in check_dropbox
    plug.entry_db.put('dropbox_cursor', changes['cursor'])
  File "onitu/escalator/client/escalator.py", line 93, in put
    self._request(protocol.cmd.PUT, key, value)
  File "onitu/escalator/client/escalator.py", line 34, in _request
    raise protocol.status.EscalatorClosed()
EscalatorClosed: The client was closed

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "onitu/drivers/dropbox/dropbox_driver.py", line 271, in run
    self.check_dropbox()
  File "onitu/drivers/dropbox/dropbox_driver.py", line 263, in check_dropbox
    plug.entry_db.put('dropbox_cursor', changes['cursor'])
  File "onitu/escalator/client/escalator.py", line 93, in put
    self._request(protocol.cmd.PUT, key, value)
  File "onitu/escalator/client/escalator.py", line 34, in _request
    raise protocol.status.EscalatorClosed()
EscalatorClosed: The client was closed
```

**Comment by k4nar** [comment]
fb75d01, 7275f64, 83fafd2, 616cb47, ae5dc50 and add594a should have fixed that.
