### ISSUE TITLE
Dropbox: can't retrive the access token

### ISSUE THREAD

**Issue by Khady** [onitu/onitu#88]
```
$ python get_access_token.py
url: https://www.dropbox.com/1/oauth/authorize?oauth_token=YZEiGJMCzS1J9XgP
Please visit this website and press the 'Allow' button,then hit 'Enter' here.

Traceback (most recent call last):
  File "get_access_token.py", line 19, in <module>
    input()
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by Scylardor** [comment]
Fixed in 0d36ed7975cf98836e3e20842d72a40d4c40375a .

Besides, we should specify somewhere (probably in the README) that due to this part of the Dropbox API being incompatible with Python 3, this script should always be ran with Python 2.
